### ISSUE TITLE
[BUG] Error on scene without background map

### ISSUE THREAD

**Issue by weepingminotaur** [ironmonk108/enhanced-terrain-layer#135] opened 2023-04-29 23:43 UTC
Got this error creating a scene without a background map.
<img width="589" alt="Screen Shot 2023-04-29 at 5 14 39 PM" src="https://user-images.githubusercontent.com/90105219/235328470-48fad443-c8fb-427a-89cd-d5f167b9f347.png">

**Comment by ironmonk88** [comment] 2023-05-27 17:04
Duplicate of #133

**Closed as completed by ironmonk88** 2023-05-27 17:04 UTC
Labels: duplicate, fixed waiting for release
