### ISSUE TITLE
"Dead" tokens in PF2e system

### ISSUE THREAD

**Issue by monkey-bars** [ironmonk108/enhanced-terrain-layer#59] opened 2021-09-29 17:37 UTC
I'm not sure how Enhanced Terrain Layer interacts with the PF2E system and what the module is looking for to consider a token "dead" for purposes of the "Dead cause difficult terrain" rule. 

There's no "Dead" condition in the PF2e system; if "Tokens cause difficult terrain" is checked, but "Dead cause difficult terrain" is not, even when tokens have 0 hp and they're Marked Defeated in the Encounter Tracker, they still count as difficult terrain.

![image](https://user-images.githubusercontent.com/38258926/135320201-94d80fc3-5ac8-4799-8a51-e833d6db41eb.png)

**Comment by velara** [comment] 2021-12-20 04:35
This is something best handled by the PF2e drag ruler integration rather than by Enhanced Terrain layer. And will be next release, assuming no bugs make me eat those words. 

Once I put out the next release, when the Dead Caused Difficult terrain setting is checked, creatures that have 0 hp, the unconscious, paralyzed, immobilized, petrified or dead conditions will be treated as difficult terrain by all creatures. 

Furthermore the Tokens Cause difficult terrain setting will now only apply to creatures that do not have the same disposition as you. Friendly creatures ignore difficult terrain caused by other friendly creatures, likewise for hostile creatures.

**Comment by ironmonk88** [comment] 2022-05-07 21:23
Closing the ticket as I think it should be covered.
But @velara I wanted to add that the next version of Enhanced Terrain will allow you to include a function in the options that can be used to "figure" out if a token is dead.  So system specific Rulers can provide their own way of determining that status to the cost function.
Easy as `cost([], { isDead: (token) => { //add code here to determine if the token is dead }})`.

**Closed as completed by ironmonk88** 2022-05-07 21:23 UTC
