### ISSUE TITLE
[BUG] Terrain drawn with the Rectangle and Ellipse tool is invalid

### ISSUE THREAD

**Issue by PepijnMC** [ironmonk108/enhanced-terrain-layer#101] opened 2022-09-27 14:34 UTC
**Describe the bug**
Terrain placed using either the rectangle or ellipse tools seems to be ignored by the cost function all together.

**To Reproduce**
1. Draw terrain using the rectangle, ellipse, and polygon tools
2. Attempt to retrieve the cost of the terrain
3. Notice that the polygon drawn terrain returns the correct movement cost while the other two return a cost of 1.

**Expected behavior**
Terrain placed using the rectangle and ellipse tools returns the correct movement cost like terrain placed by the polygon and free drawing tools.

**Comment by manuelVo** [comment] 2022-09-27 15:12
I can confirm this issue for terrain placed with the rectangle and ellipse tool. Placing terrain with the polygon tool works fine for me, however. To elaborate a bit more, terrain placed using rectangle and ellipse tool is registered by the cost function, however their location is mapped to a different part of the scene than where they were placed.

**Concrete example**
This is the only terrain that has been put down on a scene: 
![grafik](https://user-images.githubusercontent.com/1705157/192564608-9b61b5c5-5466-4d1e-90fd-893182a49e84.png)

Since the scene has no padding, the coordinates of the Terrain are `1,1`. However, as you can see from the following console screenshot, the cost function doesn't regard the terrain to be located at `1,1`, but at `3,3`.
![grafik](https://user-images.githubusercontent.com/1705157/192565439-4f3334b8-4831-432a-95ac-cb8f11bfb34e.png)

**Comment by ironmonk88** [comment] 2022-11-11 22:47
Should be fixed in the latest release.

**Closed as completed by ironmonk88** 2022-11-11 22:47 UTC
Labels: fixed waiting for release
